"use client";
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from "./components/global/SideBar";
import Header from "./components/global/Header";
import MobileSidebar from "./components/global/MobileSideBar";
import { useState } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const toggleSidebar = () => setSidebarOpen((prev) => !prev);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#151515] text-[#e0dede]`}
      >
        <div className="max-w-[1440px] w-full m-auto p-3">
          {/* <div className="sticky top-0 z-50 bg-[#151515] p-4 shadow-md rounded-xl"> */}
          <Header onLogoClick={toggleSidebar} />
          {/* </div> */}
          <div className="flex justify-between mt-10 gap-5 max-800:flex-col">
            <div
              className="
    sticky top-6
    max-h-screen
    overflow-y-auto
    scrollbar-thin scrollbar-thumb-gray-500 scrollbar-track-gray-800
    max-w-[350px] w-full
    bg-DarkGrey shadow-lg rounded-xl p-7
    max-[1000px]:max-w-[250px]
    max-[800px]:max-w-full max-[800px]:hidden
    max-[1000px]:p-3
  "
            >
              <SideBar />
            </div>
            <div className="hidden max-800:flex">
              <MobileSidebar isOpen={sidebarOpen} setIsOpen={setSidebarOpen} />
            </div>

            <div className="max-w-[1000px] w-full ">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
