import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from "./components/global/SideBar";
import Header from "./components/global/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#151515] text-[#e0dede]`}
      >
        <div className="max-w-[1440px] w-full m-auto p-5">
          <Header />
          <div className="flex justify-between my-10">
            <div className="max-w-[350px] w-full bg-DarkGrey shadow-lg rounded-xl p-7 ">
              <SideBar />
            </div>
            <div className="max-w-[1000px] w-full">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
